### ISSUE TITLE
Layer style : red color for marker not working (giving black)

### ISSUE THREAD

**Issue by kazemar** [kalisio/crisis#294]
prod version : Client v1.1.4 (1216) - API v1.1.4 (1216)

When I choose the red color for a marker I get black color
![image](https://user-images.githubusercontent.com/6574960/131466423-9d0952e9-51d4-4e41-b8c1-d02dce1f7bcd.png)

In the source code I see :
orange background
![image](https://user-images.githubusercontent.com/6574960/131466951-7a8a8b73-70eb-483d-b64c-6debcf9b9121.png)

red background
![image](https://user-images.githubusercontent.com/6574960/131467025-85dc1aca-e9e5-43f5-9b77-4e6d3c687014.png)

**Comment by claustres** [comment]
Seems to be fixed in v2
